[10-17-2024 07:57:10 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 07:57:10 AM] Starting up TCP server on localhost:65319
[10-17-2024 07:57:10 AM] Flet app has started...
[10-17-2024 07:57:11 AM] App session started
[10-17-2024 07:57:19 AM] CSV File Processing: Completed in 682ms
[10-17-2024 07:57:19 AM] Next runtime in: 3.0 minutes: Completed in 0ms
[10-17-2024 07:57:28 AM] CSV File Processing: Completed in 1990ms
[10-17-2024 07:57:28 AM] Next runtime in: 3.0 minutes: Completed in 0ms
[10-17-2024 07:57:39 AM] CSV File Processing: Completed in 2861ms
[10-17-2024 07:57:39 AM] Next runtime in: 2.0 minutes: Completed in 0ms
[10-17-2024 07:57:52 AM] CSV File Processing: Completed in 4076ms
[10-17-2024 07:57:52 AM] Next runtime in: 2.0 minutes: Completed in 0ms
[10-17-2024 07:58:06 AM] CSV File Processing: Completed in 5049ms
[10-17-2024 07:58:06 AM] Next runtime in: 2.0 minutes: Completed in 0ms
[10-17-2024 07:58:30 AM] CSV File Processing: Completed in 5613ms
[10-17-2024 07:58:30 AM] Next runtime in: 1.0 minutes: Completed in 0ms
[10-17-2024 08:00:35 AM] CSV File Processing: Completed in 35657ms
[10-17-2024 08:00:35 AM] Next runtime in: 59.0 minutes: Completed in 0ms
[10-17-2024 08:00:35 AM] CSV File Processing: Completed in 35837ms
[10-17-2024 08:00:35 AM] Next runtime in: 59.0 minutes: Completed in 0ms
[10-17-2024 08:00:35 AM] CSV File Processing: Completed in 35911ms
[10-17-2024 08:00:35 AM] CSV File Processing: Completed in 35913ms
[10-17-2024 08:00:35 AM] Next runtime in: 59.0 minutes: Completed in 0ms
[10-17-2024 08:00:35 AM] CSV File Processing: Completed in 35973ms
[10-17-2024 08:00:35 AM] CSV File Processing: Completed in 35975ms
[10-17-2024 08:00:36 AM] Next runtime in: 59.0 minutes: Completed in 0ms
[10-17-2024 08:00:36 AM] Next runtime in: 59.0 minutes: Completed in 0ms
[10-17-2024 08:00:36 AM] Next runtime in: 59.0 minutes: Completed in 0ms
[10-17-2024 08:01:30 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:01:30 AM] Starting up TCP server on localhost:65319
[10-17-2024 08:01:30 AM] Flet app has started...
[10-17-2024 08:01:30 AM] App session started
[10-17-2024 08:01:37 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:01:37 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:01:37 AM] Flet app has started...
[10-17-2024 08:01:37 AM] App session started
[10-17-2024 08:01:49 AM] CSV File Processing: Completed in 1944ms
[10-17-2024 08:01:49 AM] Next runtime in: 58.0 minutes: Completed in 0ms
[10-17-2024 08:08:18 AM] CSV File Processing: Completed in 1940ms
[10-17-2024 08:08:18 AM] Next runtime in: 52.0 minutes: Completed in 0ms
[10-17-2024 08:11:42 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:11:42 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:11:42 AM] Flet app has started...
[10-17-2024 08:11:43 AM] App session started
[10-17-2024 08:11:47 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:11:47 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:11:47 AM] Flet app has started...
[10-17-2024 08:11:47 AM] App session started
[10-17-2024 08:12:50 AM] CSV File Processing: Completed in 9605ms
[10-17-2024 08:12:50 AM] Next runtime in: 47.0 minutes: Completed in 0ms
[10-17-2024 08:17:33 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:17:33 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:17:33 AM] Flet app has started...
[10-17-2024 08:17:33 AM] App session started
[10-17-2024 08:17:37 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:17:37 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:17:37 AM] Flet app has started...
[10-17-2024 08:17:38 AM] App session started
[10-17-2024 08:17:41 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:17:41 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:17:41 AM] Flet app has started...
[10-17-2024 08:17:41 AM] App session started
[10-17-2024 08:20:23 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:20:23 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:20:23 AM] Flet app has started...
[10-17-2024 08:20:23 AM] App session started
[10-17-2024 08:20:32 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:20:32 AM] Starting up TCP server on localhost:65511
[10-17-2024 08:20:32 AM] Flet app has started...
[10-17-2024 08:20:56 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:20:56 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:20:56 AM] Flet app has started...
[10-17-2024 08:20:56 AM] App session started
[10-17-2024 08:21:07 AM] [GENERIC] INVALID FORMATS FOUND IN INPUT CSV FILE. PROCESS ABORTED
[10-17-2024 08:21:07 AM] CSV File Processing: Completed in 1898ms
[10-17-2024 08:21:07 AM] [GENERIC] Next runtime in: 39.0 minutes
[10-17-2024 08:22:28 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:22:28 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:22:28 AM] Flet app has started...
[10-17-2024 08:22:29 AM] App session started
[10-17-2024 08:22:33 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:22:33 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:22:33 AM] Flet app has started...
[10-17-2024 08:23:56 AM] App session started
[10-17-2024 08:24:36 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:24:36 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:24:36 AM] Flet app has started...
[10-17-2024 08:24:36 AM] App session started
[10-17-2024 08:24:41 AM] Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'value'")>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\main.py", line 114, in pick_file_result
    selected_files.value = (
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
[10-17-2024 08:24:44 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:24:44 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:24:44 AM] Flet app has started...
[10-17-2024 08:24:44 AM] App session started
[10-17-2024 08:24:48 AM] Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'value'")>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\main.py", line 114, in pick_file_result
    selected_files.value = (
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
[10-17-2024 08:26:25 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:26:25 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:26:25 AM] Flet app has started...
[10-17-2024 08:26:25 AM] App session started
[10-17-2024 08:26:34 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:26:34 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:26:34 AM] Flet app has started...
[10-17-2024 08:26:34 AM] App session started
[10-17-2024 08:26:43 AM] Service Closed: Completed in 0ms
[10-17-2024 08:26:53 AM] [GENERIC] INVALID DATE FORMAT FOUND IN DATETIME COLUMN. PROCESS ABORTED
[10-17-2024 08:26:53 AM] CSV File Processing: Completed in 1867ms
[10-17-2024 08:26:53 AM] [GENERIC] Next runtime in: 33.0 minutes
[10-17-2024 08:28:16 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:28:16 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:28:16 AM] Flet app has started...
[10-17-2024 08:28:16 AM] App session started
[10-17-2024 08:28:21 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:28:21 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:28:21 AM] Flet app has started...
[10-17-2024 08:28:21 AM] App session started
[10-17-2024 08:28:30 AM] [GENERIC] INVALID DATE FORMAT FOUND IN DATETIME COLUMN. PROCESS ABORTED
[10-17-2024 08:28:30 AM] CSV File Processing: Completed in 1929ms
[10-17-2024 08:28:30 AM] [GENERIC] Next runtime in: 31.0 minutes
[10-17-2024 08:29:21 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:29:21 AM] Starting up TCP server on localhost:49914
[10-17-2024 08:29:21 AM] Flet app has started...
[10-17-2024 08:29:21 AM] App session started
[10-17-2024 08:29:28 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:29:28 AM] Starting up TCP server on localhost:50152
[10-17-2024 08:29:28 AM] Flet app has started...
[10-17-2024 08:29:28 AM] App session started
[10-17-2024 08:29:40 AM] Future exception was never retrieved
future: <Future finished exception=KeyError('Datetime_is_dateime')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Datetime_is_dateime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\main.py", line 248, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\main.py", line 176, in process_file
    print(temp_read['Datetime_is_dateime'])
          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Datetime_is_dateime'
[10-17-2024 08:29:57 AM] Future exception was never retrieved
future: <Future finished exception=KeyError('Datetime_is_dateime')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Datetime_is_dateime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\main.py", line 248, in main_service
    process_file()
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\main.py", line 176, in process_file
    print(temp_read['Datetime_is_dateime'])
          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'Datetime_is_dateime'
[10-17-2024 08:30:00 AM] Service Closed: Completed in 0ms
[10-17-2024 08:30:12 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:30:12 AM] Starting up TCP server on localhost:50152
[10-17-2024 08:30:12 AM] Flet app has started...
[10-17-2024 08:30:12 AM] App session started
[10-17-2024 08:30:16 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:30:16 AM] Starting up TCP server on localhost:50152
[10-17-2024 08:30:16 AM] Flet app has started...
[10-17-2024 08:30:16 AM] App session started
[10-17-2024 08:30:24 AM] [GENERIC] INVALID DATE FORMAT FOUND IN DATETIME COLUMN. PROCESS ABORTED
[10-17-2024 08:30:24 AM] CSV File Processing: Completed in 1896ms
[10-17-2024 08:30:24 AM] [GENERIC] Next runtime in: 30.0 minutes
[10-17-2024 08:31:02 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:31:02 AM] Starting up TCP server on localhost:50152
[10-17-2024 08:31:02 AM] Flet app has started...
[10-17-2024 08:31:02 AM] App session started
[10-17-2024 08:31:06 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:31:06 AM] Starting up TCP server on localhost:50152
[10-17-2024 08:31:06 AM] Flet app has started...
[10-17-2024 08:31:15 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:31:15 AM] Starting up TCP server on localhost:50215
[10-17-2024 08:31:15 AM] Flet app has started...
[10-17-2024 08:31:16 AM] App session started
[10-17-2024 08:31:26 AM] [GENERIC] INVALID DATE FORMAT FOUND IN DATETIME COLUMN. PROCESS ABORTED
[10-17-2024 08:31:26 AM] CSV File Processing: Completed in 1958ms
[10-17-2024 08:31:26 AM] [GENERIC] Next runtime in: 29.0 minutes
[10-17-2024 08:31:29 AM] Service Closed: Completed in 0ms
[10-17-2024 08:32:05 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:32:05 AM] Starting up TCP server on localhost:50273
[10-17-2024 08:32:05 AM] Flet app has started...
[10-17-2024 08:32:06 AM] App session started
[10-17-2024 08:32:16 AM] CSV File Processing: Completed in 2163ms
[10-17-2024 08:32:16 AM] [GENERIC] Next runtime in: 28.0 minutes
[10-17-2024 08:32:23 AM] Service Closed: Completed in 0ms
[10-17-2024 08:35:12 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:35:12 AM] Starting up TCP server on localhost:50406
[10-17-2024 08:35:12 AM] Flet app has started...
[10-17-2024 08:35:12 AM] App session started
[10-17-2024 08:35:32 AM] [GENERIC] File could not be written! Is the output file opened?
[10-17-2024 08:35:32 AM] CSV File Processing: Completed in 1870ms
[10-17-2024 08:35:32 AM] [GENERIC] Next runtime in: 24.0 minutes
[10-17-2024 08:36:16 AM] CSV File Processing: Completed in 1921ms
[10-17-2024 08:36:16 AM] [GENERIC] Next runtime in: 24.0 minutes
[10-17-2024 08:36:50 AM] CSV File Processing: Completed in 10980ms
[10-17-2024 08:36:50 AM] [GENERIC] Next runtime in: 23.0 minutes
[10-17-2024 08:43:07 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:43:07 AM] Starting up TCP server on localhost:50406
[10-17-2024 08:43:07 AM] Flet app has started...
[10-17-2024 08:43:07 AM] App session started
[10-17-2024 08:43:11 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:43:11 AM] Starting up TCP server on localhost:50406
[10-17-2024 08:43:11 AM] Flet app has started...
[10-17-2024 08:43:11 AM] App session started
[10-17-2024 08:43:25 AM] Future exception was never retrieved
future: <Future finished exception=AssertionError('Text Control must be added to the page first')>
Traceback (most recent call last):
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\page.py", line 944, in wrapper
    handler(*args)
  File "C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\main.py", line 124, in pick_file_result
    selected_files.update()
  File "C:\Users\M268816\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet_core\control.py", line 308, in update
    self.__page
AssertionError: Text Control must be added to the page first
[10-17-2024 08:43:43 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:43:43 AM] Starting up TCP server on localhost:50406
[10-17-2024 08:43:43 AM] Flet app has started...
[10-17-2024 08:43:43 AM] App session started
[10-17-2024 08:43:51 AM] Assets path configured: C:\Users\M268816\OneDrive - MerckGroup\Special Projects\PowerApps\git-repo\power-repo\custom-csv-loader\assets
[10-17-2024 08:43:51 AM] Starting up TCP server on localhost:50406
[10-17-2024 08:43:51 AM] Flet app has started...
[10-17-2024 08:43:51 AM] App session started
